# Generated by Django 5.0 on 2024-02-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('picname', models.TextField(default='-')),
                ('picurl', models.TextField(default='-')),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(default='00:00', max_length=12)),
            ],
        ),
    ]
