# Generated by Django 5.0 on 2024-02-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='time',
        ),
    ]
