# Generated by Django 5.0 on 2024-01-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.TextField(default='fb'),
        ),
        migrations.AddField(
            model_name='main',
            name='google',
            field=models.TextField(default='gg'),
        ),
        migrations.AddField(
            model_name='main',
            name='pt',
            field=models.TextField(default='pt'),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.TextField(default='tw'),
        ),
    ]
