# Generated by Django 5.0 on 2024-01-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_about_main_fb_main_google_main_pt_main_tw'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='email',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='main',
            name='tell',
            field=models.CharField(default='+91 ', max_length=255),
        ),
    ]
