# Generated by Django 5.0 on 2024-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_email_main_link_main_tell'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='location',
            field=models.CharField(default='Ahmedabad, India', max_length=255),
        ),
    ]
