# Generated by Django 5.0 on 2024-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(default='fb', max_length=128),
        ),
        migrations.AlterField(
            model_name='main',
            name='google',
            field=models.CharField(default='gg', max_length=128),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(default='My Site', max_length=128),
        ),
        migrations.AlterField(
            model_name='main',
            name='pt',
            field=models.CharField(default='pt', max_length=128),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(default='tw', max_length=128),
        ),
    ]
