# Generated by Django 5.0 on 2024-01-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_main_fb_alter_main_google_alter_main_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='Site Settings', max_length=128),
        ),
    ]
