# Generated by Django 3.1.7 on 2024-02-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('product_id', models.IntegerField()),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(default='00:00', max_length=12)),
            ],
        ),
    ]
