# Generated by Django 5.0 on 2024-02-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_pic_product_picname_product_picurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.CharField(default='00:00', max_length=12),
        ),
    ]
