# Generated by Django 3.1.7 on 2024-02-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20240217_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_by',
            field=models.CharField(default='-', max_length=128),
        ),
    ]
